const dishes = [
  {
    keyword: "soup_tomato",
    name: "Сливочный томатный суп",
    price: 320,
    category: "soup",
    count: "350 мл",
    image: "images/soup-tomato.jpg",
  },
  {
    keyword: "soup_chicken",
    name: "Куриный суп с домашней лапшой",
    price: 290,
    category: "soup",
    count: "400 мл",
    image: "images/soup-chicken.jpg",
  },
  {
    keyword: "soup_pumpkin",
    name: "Тыквенный крем-суп с семечками",
    price: 340,
    category: "soup",
    count: "330 мл",
    image: "images/soup-pumpkin.jpg",
  },
  {
    keyword: "main_chicken",
    name: "Куриное филе с овощами гриль",
    price: 420,
    category: "main",
    count: "250 г",
    image: "images/main-chicken.jpg",
  },
  {
    keyword: "main_pasta",
    name: "Паста с томатным соусом и моцареллой",
    price: 410,
    category: "main",
    count: "280 г",
    image: "images/main-pasta.jpg",
  },
  {
    keyword: "main_salmon",
    name: "Запечённое филе лосося с лимоном и свежими травами",
    price: 540,
    category: "main",
    count: "230 г",
    image: "images/main-fish.jpg",
  },
  {
    keyword: "drink_mors",
    name: "Домашний морс из ягод",
    price: 180,
    category: "drink",
    count: "300 мл",
    image: "images/drink-mors.jpg",
  },
  {
    keyword: "drink_lemonade",
    name: "Лимонад с мятой и лаймом",
    price: 190,
    category: "drink",
    count: "300 мл",
    image: "images/drink-lemonade.jpg",
  },
  {
    keyword: "drink_latte",
    name: "Латте на альтернативном молоке",
    price: 230,
    category: "drink",
    count: "250 мл",
    image: "images/drink-latte.jpg",
  },
];
